baseURL                = "https://fattyyo.github.io/"
theme                  = "stack"
locale                 = "zh-tw"
title                  = "Eric 的海外日記"
defaultContentLanguage = "en"
hasCJKLanguage         = true

[pagination]
    pagerSize = 6

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
